# https://galaxy.ansible.com/linuxhq/selinux/
- src: linuxhq.selinux
  name: selinux
  version: master

# https://galaxy.ansible.com/geerlingguy/ntp/
- src: geerlingguy.ntp
  name: ntp
  version: 1.5.2

# https://galaxy.ansible.com/sansible/users_and_groups/
- src: sansible.users_and_groups
  name: users_and_groups
  version: v1.4.1

# https://galaxy.ansible.com/geerlingguy/repo-remi/
- src: geerlingguy.repo-remi
  name: remi
  version: 1.2.0

# https://galaxy.ansible.com/geerlingguy/repo-epel/
- src: geerlingguy.repo-epel
  name: epel
  version: 1.2.2

# https://galaxy.ansible.com/GROG/package/
- src: GROG.package
  name: package
  version: v1.2.4

# https://galaxy.ansible.com/officel/anyenv/
- src: officel.anyenv
  name: anyenv
  version: master

# https://galaxy.ansible.com/andrewrothstein/packer/
- src: andrewrothstein.packer
  name: packer
  version: master

# https://galaxy.ansible.com/nickhammond/logrotate/
- src: nickhammond.logrotate
  name: logrotate
  version: master

# https://galaxy.ansible.com/geerlingguy/nginx/
- src: geerlingguy.nginx
  name: nginx
  version: 2.5.0

# https://galaxy.ansible.com/geerlingguy/php/
- src: geerlingguy.php
  name: php
  version: 3.5.0

# https://galaxy.ansible.com/geerlingguy/composer/
- src: geerlingguy.composer
  name: composer
  version: 1.6.1

# https://galaxy.ansible.com/wunzeco/ssh-config/
- src: wunzeco.ssh-config
  name: ssh-config
  version: v1.1

# https://galaxy.ansible.com/geerlingguy/java/
- src: geerlingguy.java
  name: java
  version: 1.7.4

# https://galaxy.ansible.com/geerlingguy/jenkins/
- src: geerlingguy.jenkins
  name: jenkins
  version: 3.2.2

# https://galaxy.ansible.com/geerlingguy/nodejs/
- src: geerlingguy.nodejs
  name: nodejs
  version: 4.1.2

# https://galaxy.ansible.com/mackerelio/mackerel-agent/
- src: mackerelio.mackerel-agent
  name: mackerel
  version: v0.7.0

# https://galaxy.ansible.com/Datadog/datadog/
- src: Datadog.datadog
  name: datadog
  version: 1.4.0

# https://galaxy.ansible.com/franklinkim/newrelic/
- src: franklinkim.newrelic
  name: newrelic
  version: 1.7.0

# 修正して使用(roles以下)=======================================================

# # https://galaxy.ansible.com/Stouts/limits/
# - src: Stouts.limits
#   name: limits
#   version: 1.2.3

# # https://galaxy.ansible.com/wunzeco/consul/
# - src: wunzeco.consul
#   name: consul
#   version: v1.3

# # https://galaxy.ansible.com/rfhayashi/gcloud/
# - src: rfhayashi.gcloud
#   name: gcloud
#   version: 0.5

# # https://galaxy.ansible.com/geerlingguy/pip/
# - src: geerlingguy.pip
#   name: pip
#   version: 1.1.0

# # https://galaxy.ansible.com/geerlingguy/mysql/
# - src: geerlingguy.mysql
#   name: mysql
#   version: 2.8.0

# # https://galaxy.ansible.com/geerlingguy/memcached/
# - src: geerlingguy.memcached
#   name: memcached
#   version: 1.0.7

# # https://galaxy.ansible.com/DavidWittman/redis/
# - src: DavidWittman.redis
#   name: redis
#   version: 1.2.4

# https://galaxy.ansible.com/samdoran/gitlab/
# - src: samdoran.gitlab
#   name: gitlab
#   version: 3.1.2

# https://galaxy.ansible.com/geerlingguy/haproxy/
# - src: geerlingguy.haproxy
#   name: haproxy
#   version: 1.1.1

# https://galaxy.ansible.com/linuxhq/postfix/
# - src: linuxhq.postfix
#   name: postfix
#   version: master

# ==========================================================================


# 使用したことがある ===========================================================

# # https://galaxy.ansible.com/jtyr/yumrepo/
# - src: jtyr.yumrepo
#   name: yumrepo
#   version: master

# ==========================================================================
