---

- name: Configure php-fpm status
  blockinfile:
    path: "/etc/php-fpm.d/www.conf"
    marker: "; {mark} ANSIBLE MANAGED BLOCK STATUS"
    insertafter: ";pm.status_path = /status"
    block: "pm.status_path = {{ php_fpm_pm_status_path }}"
  notify: restart php-fpm

- name: Configure php-fpm ping
  blockinfile:
    path: "/etc/php-fpm.d/www.conf"
    marker: "; {mark} ANSIBLE MANAGED BLOCK PING"
    insertafter: ";ping.path = /ping"
    block: "ping.path = {{ php_fpm_ping_path }}"
  notify: restart php-fpm
