---
# tasks file for mysql_version_check

- name: Configure php-fpm status
  lineinfile:
    dest: "/etc/php-fpm.d/www.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^pm\.status_path.?=.+$'
      line: "pm.status_path = {{ php_fpm_pm_status_path }}"
  notify: restart php-fpm
