---

# 最後に実行するタスク
- name: Post Task Execute
  hosts: '{{ server }}'
  become: true
  tags: post_task
  roles:
    # mackerelインストール
    - role: ../../roles/galaxy/mackerel
      when: mackerel_flag
      mackerel_agent_apikey: "{{ install_mackerel_agent_apikey }}"
      mackerel_agent_roles: "{{ install_mackerel_agent_roles }}"
      mackerel_use_plugins: yes
      mackerel_agent_plugins: "{{ install_mackerel_agent_plugins }}"
      mackerel_check_plugins: "{{ install_mackerel_check_plugins }}"
      tags: mackerel

    # datadogインストール
    - role: ../../roles/galaxy/datadog
      when: datadog_flag
      datadog_agent6: "{{ install_datadog_agent6 }}"
      datadog_agent_version: "{{ install_datadog_agent_version }}"
      datadog_api_key: "{{ install_datadog_api_key }}"
      datadog_enabled: "{{ install_datadog_enabled }}"
      datadog_config: "{{ install_datadog_config }}"
      datadog_config_ex: "{{ install_datadog_config_ex }}"
      datadog_checks: "{{ install_datadog_checks }}"
      tags: datadog

    # newrelicインストール
