---

# 最後に実行するタスク
- name: Post Task Execute
  hosts: '{{ server }}'
  become: true
  tags: post_task
  roles:
    # mackerelインストール
    - role: ../../roles/galaxy/mackerel
      when: mackerel_flag
      mackerel_agent_apikey: "{{ install_mackerel_agent_apikey }}"
      mackerel_agent_roles: "{{ install_mackerel_agent_roles }}"
      mackerel_use_plugins: yes
      mackerel_agent_plugins: "{{ install_mackerel_agent_plugins }}"
      mackerel_check_plugins: "{{ install_mackerel_check_plugins }}"
      tags: mackerel

    - role: ../../roles/galaxy/users_and_groups
      when: datadog_flag
      users_and_groups:
        groups: []
        users: []
        sudoers:
          - name: dd-agent
            user: "%dd-agent"
            runas: "ALL=(ALL)"
            commands: "NOPASSWD:/usr/bin/find"
        whitelist_groups: []
        authorized_keys_dir: ~
      tags: datadog

    # datadogインストール
    - role: ../../roles/galaxy/datadog
      when: datadog_flag
      datadog_agent5: "{{ install_datadog_agent5 }}"
      datadog_agent_version: "{{ install_datadog_agent_version }}"
      datadog_api_key: "{{ install_datadog_api_key }}"
      datadog_enabled: "{{ install_datadog_enabled }}"
      datadog_config: "{{ install_datadog_config }}"
      datadog_config_ex: "{{ install_datadog_config_ex }}"
      datadog_checks: "{{ install_datadog_checks }}"
      tags: datadog

    # newrelicインストール
    - role: ../../roles/galaxy/newrelic
      when: newrelic_flag
      newrelic_license_key: "{{ install_newrelic_license_key }}"
      newrelic_service_state: "{{ install_newrelic_service_state }}"
      newrelic_labels: "{{ install_newrelic_labels }}"
      tags: newrelic
