---

- name: Reboot tasks
  hosts: '{{ server }}'
  become: true
  tags: reboot
  tasks:
    - name: Reboot Target Server
      shell: "sleep 2 && reboot"
      async: 5
      poll: 0
      ignore_errors: true

    - name: Waiting for server to come back
      become: false
      local_action:
        module: wait_for
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 30
        timeout: 300
