---

## Installation options
redis_version: 2.8.9
redis_install_dir: /opt/redis
redis_download_url: "http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz"
# Set this to true to validate redis tarball checksum against vars/main.yml
redis_verify_checksum: false
# Set this value to a local path of a tarball to use for installation instead of downloading
redis_tarball: false
# Set this to true to build 32-bit binaries of Redis
redis_make_32bit: false

redis_user: redis
redis_group: "{{ redis_user }}"

# The open file limit for Redis/Sentinel
redis_nofile_limit: 16384

## Role options
# Configure Redis as a service
# This creates the init scripts for Redis and ensures the process is running
# Also applies for Redis Sentinel
redis_as_service: true
# Add local facts to /etc/ansible/facts.d for Redis
redis_local_facts: true
# Service name
redis_service_name: "redis_{{ redis_port }}"

# config setting ========================================
redis_bind: 127.0.0.1
redis_protected_mode: yes
redis_port: 6379
redis_tcp_backlog: 511
redis_socket_path: false
redis_socket_perm: 700
redis_timeout: 0
redis_tcp_keepalive: 300
redis_daemonize: "no"
redis_supervised: "no"
redis_pidfile: /var/run/redis/{{ redis_port }}.pid
redis_loglevel: notice
redis_logfile: /var/log/redis/redis.log
redis_syslog_enabled: "no"
redis_syslog_ident: "{{ redis_service_name }}"
redis_syslog_facility: local0
redis_databases: 16
redis_save:
  - 900 1
  - 300 10
  - 60 10000
redis_stop_writes_on_bgsave_error: "yes"
redis_rdbcompression: "yes"
redis_rdbchecksum: "yes"
redis_dbfilename: dump.rdb
redis_dir: /var/lib/redis/{{ redis_port }}
redis_slaveof: false
redis_slave_serve_stale_data: "yes"
redis_slave_read_only: "yes"
redis_repl_diskless_sync: "no"
redis_repl_diskless_sync_delay: 5
redis_repl_disable_tcp_nodelay: "no"
redis_repl_backlog_size: false
redis_slave_priority: 100
redis_min_slaves_to_write: false
redis_min_slaves_max_lag: false
redis_password: false
redis_rename_commands: []
redis_maxclients: 10000
redis_maxmemory: false
redis_maxmemory_policy: noeviction
redis_appendonly: "no"
redis_appendfilename: "appendonly.aof"
redis_appendfsync: "everysec"
redis_no_appendfsync_on_rewrite: "no"
redis_auto_aof_rewrite_percentage: "100"
redis_auto_aof_rewrite_min_size: "64mb"
redis_aof_load_truncated: "yes"
redis_lua_time_limit: 5000
redis_cluster_enabled: "no"
redis_cluster_config_file: nodes-{{ redis_port }}.conf
redis_cluster_node_timeout: 15000
redis_cluster_slave_validity_factor: 10
redis_cluster_migration_barrier: 1
redis_cluster_require_full_coverage: "yes"
redis_slowlog_log_slower_than: 10000
redis_slowlog_max_len: 128
redis_latency_monitor_threshold: 0
redis_notify_keyspace_events: '""'
redis_hash_max_ziplist_entries: 512
redis_hash_max_ziplist_value: 64
redis_list_max_ziplist_size: -2
redis_list_compress_depth: 0
redis_set_max_intset_entries: 512
redis_zset_max_ziplist_entries: 128
redis_zset_max_ziplist_value: 64
redis_hll_sparse_max_bytes: 3000
redis_activerehashing: "yes"
redis_client_output_buffer_limit:
  - normal 0 0 0
  - slave 256mb 64mb 60
  - pubsub 32mb 8mb 60
redis_hz: 10
redis_aof_rewrite_incremental_fsync: "yes"

# =======================================================

# sentinel config setting ===============================
redis_sentinel: false
redis_sentinel_dir: /var/lib/redis/sentinel_{{ redis_sentinel_port }}
redis_sentinel_bind: 0.0.0.0
redis_sentinel_port: 26379
redis_sentinel_pidfile: /var/run/redis/sentinel_{{ redis_sentinel_port }}.pid
redis_sentinel_logfile: '""'
redis_sentinel_syslog_ident: sentinel_{{ redis_sentinel_port }}
redis_sentinel_monitors:
  - name: master01
    host: localhost
    port: 6379
    quorum: 2
    auth_pass: ant1r3z
    down_after_milliseconds: 30000
    parallel_syncs: 1
    failover_timeout: 180000
    notification_script: false
    client_reconfig_script: false

# =======================================================
