---

- name: Mail Server Tasks
  hosts: mail
  become: true
  tags: mail
  roles:
    # リレーホスト設定
    - role: ../roles/galaxy/postfix
      postfix_inet_interfaces: [ 'all' ]
      postfix_mynetworks: [ '0.0.0.0/0' ]
      postfix_relayhost: "{{ setting_postfix_relayhost }}"

  tasks:
    - name: Ignore mail health check log
      blockinfile:
        path: /etc/rsyslog.conf
        insertbefore: mail.*
        block: |
          if $msg contains '130.211.0' or $msg contains '130.211.1' or $msg contains '130.211.2' or  $msg contains '130.211.0' or $msg contains '35.191' then /var/log/mail_healthcheck.log
          & ~
      register: hc_setting

    - name: Restart rsyslog
      when: hc_setting.changed
      service:
        name: rsyslog
        state: restarted
