# redisバージョン
install_redis_version: 3.2.11

# redis port
#
# 下記バグのため一時直指定対応 - 手動修正
# https://github.com/DavidWittman/ansible-redis/issues/150
install_redis_port: 6379

# redis タイムアウト
install_redis_timeout: 120

# redis max memory
install_redis_maxmemory: "1gb"

# mackerel設定
install_mackerel_agent_plugins:
  mackerel-plugin-inode: "/usr/local/bin/mackerel-plugin-inode"
  mackerel-plugin-linux: "/usr/local/bin/mackerel-plugin-linux"
  mackerel-plugin-mailq: "/usr/local/bin/mackerel-plugin-mailq -M postfix"

  mackerel-plugin-redis: "/usr/local/bin/mackerel-plugin-redis -port=6379"

install_mackerel_check_plugins:
  check-ntpoffset: "/usr/local/bin/check-ntpoffset -w=500"
  check-redis_reachable: "/usr/local/bin/check-redis reachable --host=127.0.0.1 --port=6379"

  check-procs-redis: "/usr/local/bin/check-procs --pattern '/opt/redis/bin/redis-server 0.0.0.0:6379'"

  check-tcp-6379: "/usr/local/bin/check-tcp -p 6379"

# datadog設定
install_datadog_checks:
  process:
    init_config:
      min_collection_interval: 15
    instances:
      - name: sshd
        search_string: ['sshd']
      - name: rsyslogd
        search_string: ['rsyslogd']
      - name: postfix
        search_string: ['/usr/libexec/postfix/master']
        exact_match: false
      - name: ntpd
        search_string: ['ntpd']
      - name: consul
        search_string: ['consul']
      - name: redis
        search_string: ['redis-server']
  tcp_check:
    init_config:
      min_collection_interval: 15
    instances:
      - name: ssh 22
        host: 127.0.0.1
        port: 22
        skip_event: true
      - name: postfix 25
        host: 127.0.0.1
        port: 25
        skip_event: true
      - name: consul 8301
        host: 127.0.0.1
        port: 8301
        skip_event: true
      - name: consul 8500
        host: 127.0.0.1
        port: 8500
        skip_event: true
      - name: consul 8600
        host: 127.0.0.1
        port: 8600
        skip_event: true
      - name: redis 6379
        host: 127.0.0.1
        port: 6379
        skip_event: true
  postfix:
    init_config:
    instances:
      - directory: /var/spool/postfix
        queues:
          - incoming
          - active
          - deferred
  redisdb:
    init_config:
    instances:
      - host: localhost
        port: 6379

