# nodeバージョン
install_nodejs_version: "6.x"

# npmパッケージ
npm_packages:
  - name: pm2

# 配置ディレクトリ
swagger_editor_dir: "/home/{{ public_execute_user }}/swagger_editor"
# swagger_editorバージョン
swagger_editor_version: "v3.1.18"

# datadog設定
install_datadog_checks:
  process:
    init_config:
      min_collection_interval: 15
    instances:
      - name: sshd
        search_string: ['sshd']
      - name: rsyslogd
        search_string: ['rsyslogd']
      - name: postfix
        search_string: ['/usr/libexec/postfix/master']
        exact_match: false
      - name: ntpd
        search_string: ['ntpd']
      - name: consul
        search_string: ['consul']
      - name: swagger
        search_string: ["/home/{{ public_execute_user }}/swagger_editor/node_modules/.bin/npm-run-all", "/home/{{ public_execute_user }}/swagger_editor/node_modules/.bin/http-server"]
        exact_match: false
  tcp_check:
    init_config:
      min_collection_interval: 15
      skip_event: true
    instances:
      - name: ssh 22
        host: 127.0.0.1
        port: 22
        skip_event: true
      - name: postfix 25
        host: 127.0.0.1
        port: 25
        skip_event: true
      - name: consul 8301
        host: 127.0.0.1
        port: 8301
        skip_event: true
      - name: consul 8500
        host: 127.0.0.1
        port: 8500
        skip_event: true
      - name: consul 8600
        host: 127.0.0.1
        port: 8600
        skip_event: true
      - name: swagger 3001
        host: 127.0.0.1
        port: 3001
        skip_event: true
