# mysql===================================

# mysql rpm
unittest_install_mysql_repo_rpm: "https://dev.mysql.com/get/mysql57-community-release-el6-11.noarch.rpm"
# mysqlリポジトリ
unittest_install_mysql_enablerepo: "mysql57-community"
# mysqlメジャーバージョン
unittest_install_mysql_major_version: "5.7"
# mysqlバージョン
unittest_install_mysql_version: "{{ unittest_install_mysql_major_version }}.20"
# mysqlパッケージ(依存関係があるので順番を変更しないようにして下さい)
unittest_install_mysql_packages:
  - mysql-community-server-{{ unittest_install_mysql_version }}
  - mysql-community-common-{{ unittest_install_mysql_version }}
  - mysql-community-client-{{ unittest_install_mysql_version }}
  - mysql-community-devel-{{ unittest_install_mysql_version }}
  - mysql-community-libs-{{ unittest_install_mysql_version }}
  - mysql-community-libs-compat-{{ unittest_install_mysql_version }}
  - mysql-community-embedded-{{ unittest_install_mysql_version }}
  - mysql-community-embedded-devel-{{ unittest_install_mysql_version }}
  - postfix
# (依存関係があるので順番を変更しないようにして下さい)
unittest_install_mysql_packages_not_version:
  - postfix
  - mysql-community-server
  - mysql-community-client
  - mysql-community-embedded-devel
  - mysql-community-embedded
  - mysql-community-devel
  - mysql-community-libs-compat
  - mysql-community-libs
  - mysql-community-common

# mysqlユーザ
unittest_mysql_root_user_password: "{{ unittest_root_user_password_vault }}"
unittest_install_mysql_users:
  - name: deploy_user
    host: "172.%"
    password: "{{ unittest_deploy_user_password_vault }}"
    priv: "*.*:INSERT,UPDATE,DELETE,CREATE,DROP,SELECT,ALTER,INDEX,SHOW VIEW,LOCK TABLES"
  - name: update_user
    host: "172.%"
    password: "{{ unittest_update_user_password_vault }}"
    priv: "*.*:INSERT,UPDATE,DELETE,SELECT"
  - name: select_user
    host: "172.%"
    password: "{{ unittest_select_user_password_vault }}"
    priv: "*.*:SELECT"
  - name: mackerel_user
    host: "127.0.0.1"
    password: "{{ unittest_mackerel_user_password_vault }}"
    priv: "*.*:SELECT,PROCESS,REPLICATION CLIENT"
  - name: datadog_user
    host: "127.0.0.1"
    password: "{{ unittest_datadog_user_password_vault }}"
    priv: "*.*:SELECT,PROCESS,REPLICATION CLIENT"

# innodb buffer サイズ
install_mysql_innodb_buffer_pool_size: "1G"
install_mysql_slow_query_time: "0.5"
install_mysql_log_queries_not_using_indexes: "1"

# my.cnf
install_mysql_mysqldump_max_allowed_packet: "64M"
install_mysql_max_connections: "300"
install_mysql_max_connect_errors: "1000000"
install_mysql_wait_timeout: "3600"
install_mysql_max_allowed_packet: "64M"
install_mysql_thread_cache_size: "100"
install_mysql_sort_buffer_size: "1M"
install_mysql_read_buffer_size: "1M"
install_mysql_read_rnd_buffer_size: "4M"

#=========================================


# memcache================================
# memcacheバージョン
unittest_install_memcached_version: "1.5.2"
# chksum sha256 https://fossies.org/linux/www/
unittest_install_memcached_checksum: 9ac93113bdb5d037e79c61277386564ac2e5e31d49e594f11e554e4c149b7245
# memcache memory limit
unittest_install_memcached_memory_limit: 1024

#=========================================

# redis===================================
# redisバージョン
unittest_install_redis_version: 3.2.11
# redis port
#
# 下記バグのため一時直指定対応
# https://github.com/DavidWittman/ansible-redis/issues/150
unittest_install_redis_port: 6379
# redis タイムアウト
unittest_install_redis_timeout: 120
# redis max memory
unittest_install_redis_maxmemory: "1gb"

#=========================================

# php=====================================
# phpバージョン
unittest_install_php_version: "7.1.11"

# インストールに必要なリポジトリ
unittest_install_php_enablerepo: "remi-php71,remi"
# phpインストールパッケージ
unittest_install_php_packages:
  - php-{{ unittest_install_php_version }}
  - php-cli-{{ unittest_install_php_version }}
  - php-common-{{ unittest_install_php_version }}
  - php-fpm-{{ unittest_install_php_version }}
  - php-mbstring-{{ unittest_install_php_version }}
  - php-opcache-{{ unittest_install_php_version }}
  - php-pdo-{{ unittest_install_php_version }}
  - php-xml-{{ unittest_install_php_version }}
  - php-xmlrpc-{{ unittest_install_php_version }}
  - php-mcrypt-{{ unittest_install_php_version }}
  - php-process-{{ unittest_install_php_version }}
  - php-mysqlnd-{{ unittest_install_php_version }}
  - php-bcmath-{{ unittest_install_php_version }}
  - php-intl-{{ unittest_install_php_version }}
  - php-pecl-apcu
  - php-pecl-memcached
  - php-pecl-redis
  - php-pecl-msgpack
  - php-pecl-zip
  - php-pear
  - php-timecop
# phpインストールパッケージ
unittest_install_php_packages_not_version:
  - php
  - php-cli
  - php-common
  - php-fpm
  - php-mbstring
  - php-opcache
  - php-pdo
  - php-xml
  - php-xmlrpc
  - php-mcrypt
  - php-process
  - php-mysqlnd
  - php-bcmath
  - php-intl
  - php-pecl-apcu
  - php-pecl-memcached
  - php-pecl-redis
  - php-pecl-msgpack
  - php-pecl-zip
  - php-pear
  - php-timecop
# composerバージョン
unittest_install_composer_version: "1.5.2"

#=========================================

# mackerel設定
install_mackerel_agent_plugins:
  mackerel-plugin-inode: "/usr/local/bin/mackerel-plugin-inode"
  mackerel-plugin-linux: "/usr/local/bin/mackerel-plugin-linux"
  mackerel-plugin-mailq: "/usr/local/bin/mackerel-plugin-mailq -M postfix"

  mackerel-plugin-memcached: "/usr/local/bin/mackerel-plugin-memcached"

install_mackerel_check_plugins:
  check-ntpoffset: "/usr/local/bin/check-ntpoffset -w=500"
  check-memcached: "/usr/local/bin/check-memcached -k CheckKey"

  check-procs-mysqld: "/usr/local/bin/check-procs --pattern /usr/sbin/mysqld"
  check-procs-memcache: "/usr/local/bin/check-procs --pattern memcached"

  check-tcp-3306: "/usr/local/bin/check-tcp -p 3306"
  check-tcp-11211: "/usr/local/bin/check-tcp -p 11211"

# datadog設定
install_datadog_checks:
  process:
    init_config:
      min_collection_interval: 15
    instances:
      - name: sshd
        search_string: ['sshd']
      - name: rsyslogd
        search_string: ['rsyslogd']
      - name: postfix
        search_string: ['/usr/libexec/postfix/master']
        exact_match: false
      - name: ntpd
        search_string: ['ntpd']
      - name: consul
        search_string: ['consul']
      - name: mysqld
        search_string: ['mysqld', 'mysqld_safe']
      - name: memcached
        search_string: ['memcached']
  tcp_check:
    init_config:
      min_collection_interval: 15
    instances:
      - name: ssh 22
        host: 127.0.0.1
        port: 22
        skip_event: true
      - name: postfix 25
        host: 127.0.0.1
        port: 25
        skip_event: true
      - name: consul 8301
        host: 127.0.0.1
        port: 8301
        skip_event: true
      - name: consul 8500
        host: 127.0.0.1
        port: 8500
        skip_event: true
      - name: consul 8600
        host: 127.0.0.1
        port: 8600
        skip_event: true
      - name: mysql 3306
        host: 127.0.0.1
        port: 3306
        skip_event: true
      - name: memcache 11211
        host: 127.0.0.1
        port: 11211
        skip_event: true
  postfix:
    init_config:
    instances:
      - directory: /var/spool/postfix
        queues:
          - incoming
          - active
          - deferred
